source 'https://www.rubygems.org'
gem "jekyll", "~> 1.5.1"
gem 'directory_watcher', "~> 1.5.1"
gem 'guard'
gem 'guard-jekyll-plus'
gem 'guard-livereload'
gem 'sequel'
gem 'byebug'
gem 'pygmentize'
gem 'chronic'
gem 'google-api-client'
gem 'psych'
gem 'htmlentities'
gem 'deadweight'
gem 'rspec'
gem 'rake'

gem 'kramdown'
gem 'mail'
gem 's3_website'
