source 'https://www.rubygems.org'
gem 'jekyll'
gem 'directory_watcher', '=1.4.1'
gem 'sequel'
gem 'mysqlplus'
gem 'pygmentize'
gem 'chronic'
gem 'google-api-client'
gem 'psych'
gem 'htmlentities'
gem 'deadweight'

#gem 'pandoc-ruby'
#gem 'rdiscount'
gem 'kramdown'
